[package]
name = "consensus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
omnipaxos   = { git = "https://github.com/haraldng/omnipaxos", rev = "36dd86d" }
hocon       = { version = "0.5.2" }
kompact     = { git = "https://github.com/kompics/kompact", rev = "e9deae8" }
arc-runtime = { path = "../../" }
rand        = { version = "0.8.4" }
