name: test

on:
  pull_request:
    paths:
      - "arc-lang"
      - "arc-mlir"
      - "arc-runtime"
      - "arc-python"
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    env:
      CARGO_TERM_COLOR: always
      CCACHE_CONFIGPATH: /home/arc-runner/actions-runner/persist/ccache-config
      PERSIST_DIR: /home/arc-runner/actions-runner/persist/

    steps:

      # Checkout branch which we want to test
    - name: Checkout source
      uses: actions/checkout@v2

      # Update LLVM dependency
    - name: Update submodule
      run: git submodule update --init --recursive

    - name: Check ccache setup
      run: ./.github/continuous-integration.sh check-ccache

    - name: Build MLIR + LLVM + arc-lang
      run: ./.github/continuous-integration.sh run-mlir-build
      env:
        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}

    - name: Pre-build arc-runtime
      run: ./.github/continuous-integration.sh cargo test
      env:
        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}

    - name: Run MLIR tests
      run: ./.github/continuous-integration.sh run-mlir-tests
      env:
        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}

    - name: "Run arc-runtime test: clippy"
      run: ./.github/continuous-integration.sh cargo clippy
      env:
        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}

    - name: "Ccache/Sccache statistics"
      run: ./.github/continuous-integration.sh check-ccache

#    - name: "Run arc-runtime test: fmt -- -v --check"
#      run: ./.github/continuous-integration.sh cargo fmt -- -v --check
#      env:
#        A2M_BUILD: ${{ format('{0}/build', runner.temp) }}

    - name: Check for dirty tree
      run: ./check-for-dirty-tree
